### ISSUE TITLE
K-Meter closes down Tracktion 5

### ISSUE THREAD

**Issue by grunnen** [mzuther/K-Meter#9] opened 2014-11-29 21:21 UTC
Hi Martin,

At first. I like the K-Meter. I used it at first for digitizing audio cassettes.
For lining up I put a cassette with 400Hz @ 0dB in the cassette player,
set up the audio editor @ 0dB on the K-Meter (K14) and go!
This was done with an older Cubase version and a Presonus 1394 interface.

But. I have an Issue:

Setup:
ASUS laptop
Windows 7 Ultimate, 32 bit.
Tracktion 5.4.2. (29nov2014)
K-Meter 1.31.0 (VST3)
Mackie 1220 with Firewire interface.

I added the plugin to a channel (does not matter if it has 2 inputs or one).
In the active K-Meter plugin I clicked RMS (with that you set the meter into 
stereo) and instead of showing an error Tracktion 5 is closed completely.
Just like that.
I also tried the plugin in the master section of Tracktion 5 and then everything
was OK: you can do what you want

Question:
Is it possible to add a warning and have K-Meter prevent closing down T5?

Thanks for looking into this.

Regards,

Harry

**Comment by mzuther** [comment] 2015-02-19 20:52
Hi Harry,

sorry for having you wait, I was pretty busy...

I am currently rewriting K-Meter, so if you contact me (see my homepage for an email address), I'll send you a beta version.  Maybe I've already solved the problem... :)

Regards,

Martin

**Comment by jazzman31** [comment] 2015-02-19 20:54
Hey Martin,
Please send me the beta version :)

Thanks

Ümit Ceyhan

**Comment by mzuther** [comment] 2015-02-19 23:36
Hi Ümit!

Or, if I'm correct in assuming you have Turkish heritage:

Merhabalar Ümit! :)

I tried to send you the beta version of K-Meter VST.  However, Github 
rejected the email due to its big size.  So if you could send me your 
*real* email address, I'll try again.

Best regards (or: Selamlar),

Martin

-- 
www.mzuther.de
www.radix-musik.de

**Comment by mzuther** [comment] 2015-02-19 23:39
Hi Ümit!

It's too late, I should be in bed... :)

My email address is "code@mzuther.de".

Regards,

Martin

-- 
www.mzuther.de
www.radix-musik.de

**Comment by jazzman31** [comment] 2015-02-19 23:40
Merhabalar Martin,
Yes, you’re right I’m from Turkey :) 
and I’m living in france for 12 years… 
my email address is : uimtceyhan@me.com


Please send me your beta version and your email address so we can discuss…
Danke

Ümit

**Comment by mzuther** [comment] 2015-05-27 19:10
Any news regarding the beta version I sent you?

**Comment by grunnen** [comment] 2015-05-28 07:51
Hi Martin,

    I must have sent my findings regarding kmeter-vst_1.40.1 already?

    Below a copy of the text.

    Table of contents:
    A* Setup
    B* K-METER TESTS on T4 or T5 or T6
    *1. kmeter-vst_1.31
    *2. kmeter-vst_1.40.1
    C* CONCLUSION

    A* Setup:
    Windows 7.
    No connection to internet and no virus scanner active.

    Applications tested (either T4 or T5 or T6 active):
    T4: Tracktion Version 4.5.6 (Built: 5 December 2013) (32-bit)
    T5: Tracktion Version 5.4.2 (Built: 27 November 2014) (32-bit)
    T6: Tracktion Version 6.0.16 (Built: 13 February 2015) (32-bit) - Trial
    mode since the new features are not so interesting for me to buy the
upgrade.
    Attached "tracktionscreenshot.jpg" as an example of how the system
looks like.

    VST Folder K-Meter: C:\Program Files\Common Files\VST\mzuther
    A different VST folder did not have any influence onto the test.
    Everytime I made a change to the VST files I cleared the plugins list
of Tracktion
    T4 or T5 or T6 and carried out a new full scan for new plugins.

    First I reinstalled T5 before test.
    T4 was not reinstalled though. I learned during the tests that this T5
reinstall
    was not necessary since T4 responded the same way as T5. T6 was
installed after the
    tests with T4 and T5. T6 responded slightly different.
    I was not able to reproduce the original failure "shutdown of Tracktion
after
    clicking RMS of the K-meter" again.
    Shutdown = completely closing T4 or T5 ot T6 as if you pressed the
right top X.
    Some restarts of the computer did not change anything either.
    Strange though that the failure did not occur anymore. But...
    I do remember that in between the request at Github and your response I
followed some,
    not all, of the audio settings of the laptop according to:
    MusicXP.net Tuning Tips for Recording Musicians. Some XP settings work
fine in Windows 7 too.
    Link:
http://www.scribd.com/doc/51266296/MusicXP-net-Tuning-Tips-for-Recording-Musicians#scribd
    I do not recall having tested the K-meter short after the changes.

    B* K-METER TESTS on T4 or T5 or T6:

    *1. kmeter-vst_1.31 :
    The plugins scan of Tracktion shows V4.1.0 by the way. Check attached
    "libfftw3f-3_dll_loaderror.jpg".
    All .dll files were copied into the above mentioned VST folder.
    Rescan in T5 and T6 gives the message that libfftw3f-3.dll did not load
correctly.
    Check attached JPG "libfftw3f-3_dll_loaderror.jpg".
    But the K-Meter plugin worked fine in a track and also in the master
section.
    T4 did not show this message and worked as T5 and T6.

    libfftw3f-3.dll :
    When removed (and of course a rescan for VST carried out) and trying to
add the
    K-meter plugin to the track or master section then T4, T5 and T6 shut down.

    Shortcut f - (T4 or T5 or T6 - plugin disable/enable) :
    Disabling the plugin with shortcut f have T4 and T5 close just like
that. T6 was OK.
    Track and meter selected with mouse click: f causes no shutdown of  
T4 and T5
    (enabling or disabling with f works fine).
    Track and meter not selected with mouse click: f shuts down T4 and T5.
T6 was OK.
    The meter has to be selected to prevent shutdown.
    Master and meter selected or not selected with mouse click: f causes
shutdown of
    T4 and T5 in both cases. T6 was OK.
    Personally I do not find this a big issue since I know about it. But
the original
    Tracktion plugins responded correctly.

    *2. kmeter-vst_1.40.1 :
    The plugins scan of Tracktion shows V5.0.1 by the way...
    All .dll files were copied into the above mentioned VST folder.
    Rescan in T5 and T6 gives the message that libfftw3f-3.dll did not load
correctly.
    Check attached JPG "libfftw3f-3_dll_loaderror.jpg".
    The K-Meter plugin loaded fine in a track and also in the master
section but, only as a
    small window. Check attached "kmeter1401.jpg": it shows no meter, only
a small window.

    libfftw3f-3.dll :
    When removed (and of course a rescan for VST carried out) and trying to
add the
    K-meter plugin to the track or master section then T4, T5 and T6 shut down.

    Shortcut f - (T4 or T5 or T6 - plugin disable/enable) :
    Same issue with shortcut f as above for T4 and T5.
    T6 did not shutdown and responded correctly like the Tracktion plugins.

    C* CONCLUSION:
    RMS failure did not occur in T4 or T5 or T6 anymore due to possibe
setting changes
    according to MusicXP.
    T6 responded perfect, like the normal Tracktion plug-ins, with both
K-Meter versions.
    Even with the libfftw3f-3.dll error.
    "kmeter-vst_1.40.1" does not show the meter in T4 or T5 or T6: only a
small black window.

    I trust to have provided some insight?

    If you want some more tests carried out then please let me know.

    Regards,

    Harry Smit
E: hsmit@dds.nl

    Martin Zuther <notifications@github.com> schreef:
>
> Any news regarding the beta version I sent you?
>
> —
>    Reply to this email directly or view it on GitHub[1].
>  
>
>




Links:
------
[1] https://github.com/mzuther/K-Meter/issues/9#issuecomment-106038676

**Comment by mzuther** [comment] 2015-05-28 16:06
Hi Harry,

now I remember -- I thought that was a different issue.  Sorry.  But now 
your answer is not only in my email client, but also in the bug report. 
  That can't hurt.

Thanks again for all the work you put into your report.  And I'm sorry 
that I haven't found the time to look into this issue so far.

Martin

**Comment by mzuther** [comment] 2015-12-20 18:32
Hi Harry,

I have just released a new version of K-Meter with a lot of internal changes.  Maybe it solves you problems?

Have a merry Christmas!

Martin

**Comment by mzuther** [comment] 2018-01-31 21:56
Duplicate of #21. Could you please subscribe there so I can merge several issues with essentially the same problem? Thanks!

**Closed by mzuther** 2018-01-31 21:56 UTC
