### ISSUE TITLE
K-Meter fails to show in Reaper

### ISSUE THREAD

**Issue by JackMan73** [mzuther/K-Meter#12] opened 2016-09-10 21:05 UTC
Using Reaper v5.24 on Windows 7 32bit. Installed to vst folder and rescanned several times. Does not appear in Reapers list of plugins. Below are the entries in Reaper's vst ini file - note the missing info for K-meter vs trakmeter. This suggests K-meter has failed to initialize properly. trakmeter works fine.

K_Meter__Stereo_.dll=014940D4A20BD201
K_Meter__Surround_.dll=195C53D4A20BD201
libfftw3f_3.dll=4B08E5D3A20BD201
traKmeter__Multi_.dll=5830CA1AA60BD201,1953653099,traKmeter (Multi) (Martin Zuther) (8ch)
traKmeter__Stereo_.dll=62C8FB1AA60BD201,1953653099,traKmeter (Stereo) (Martin Zuther)

**Comment by mzuther** [comment] 2016-09-11 09:59
I'm sorry to hear this. Please download and install the [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) for 32 bit (x86). Does this solve the problem? If not, you could also try to install the 64-bit (amd64) redistributable, at least if you are on a 64-bit system.

Please report back so I can update / correct the documentation!

**Comment by JackMan73** [comment] 2016-09-12 05:02
Thanks for your reply. I did already have that installed, so I chose repair but got the same results. Maybe I'll try an unistall/reinstall and see if that helps. However, I suspect that something else unknown on my system may be causing the problem.

**Comment by JackMan73** [comment] 2016-09-12 20:26
Just wanted to add that the standalone version also fails to execute - no error msg. Is it possible that some dependencies of libfftw3f-3.dll are required?

**Comment by mzuther** [comment] 2016-10-03 12:34
In order to release new versions of K-Meter, I had to move to Windows 10. This has cerated problems for several users. I'm currently looking into this.

Until the problem is resolved, you can find downloads for the older version 2.2.0 on my website.

**Comment by mzuther** [comment] 2016-10-07 20:32
K-Meter 2.6.0 runs just fine on a clean Windows 7 64-bit system with nothing but Reaper installed.

Anyway, I have just released K-Meter 2.6.1 which displays an error window if the FFTW DLL was not found when K-Meter is started. Could you please try whether the new stereo stand-alone and the VST plug-in (after cleaning the plug-in cache) run on your system? Thanks!

**Comment by mzuther** [comment] 2018-01-31 21:55
Duplicate of #21. Could you please subscribe there so I can merge several issues with essentially the same problem? Thanks!

**Closed by mzuther** 2018-01-31 21:55 UTC
