### ISSUE TITLE
64-bit K-Meter 2.6.1 VST does not show in Ableton Live, and the stand-alone version crashes.

### ISSUE THREAD

**Issue by alkymi** [mzuther/K-Meter#18] opened 2017-11-04 13:05 UTC
Hi,

I have Windows 7 64-bit, and using my 64-bit version of Live, the VST configuration of K-Meter 2.6.1 does not show in the plug-in browser. Version 2.2.0 works however. Also, the stand-alone 64-bit version of K-Meter 2.6.1 does not work on my system, it crashes upon launching the application.

Cheers!

**Comment by mzuther** [comment] 2018-01-31 21:55
Duplicate of #21. Could you please subscribe there so I can merge several issues with essentially the same problem? Thanks!

**Closed by mzuther** 2018-01-31 21:55 UTC
